name: Push Main Test

on:
  push:
    branches: [ main ]

jobs:
  run_test:
    name: Run Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call Reusable Workflow
        uses: ./.github/reuse.yml
